### ISSUE TITLE
Some minor typos

### ISSUE THREAD

**Issue by erich666** [javagl/gltfOverview#1]
In the "scenes, nodes, cameras, animations" section is the passage "the data accessors.During the" - there should be a space before "During".

A few periods missing at ends of sentences, e.g. the lower left and lower right in "Computing the joint matrices for the skin".

In "More about vertex skinning", change "can not" to "cannot" - either is fine, but "cannot" is the common form.

Hmm, I had another one, but I forgot it...

**Comment by javagl** [comment]
Thanks for these hints. 

As they are not "critical" (in the sense that they do not convey any wrong information), I'll update these together with the update for glTF 1.0.1, which is likely to come soon.

**Comment by erich666** [comment]
I agree, these are minor and don't in any way impact comprehension. Just FYI for some day in the future.
